import type { AlchemyConfig } from '../types/alchemy.js';

export function generateEnvTemplate(config: AlchemyConfig): string {
  const lines: string[] = [];

  lines.push('# Environment Variables for Alchemy');
  lines.push('# Generated by alchemy-migrator');
  lines.push('');

  // Cloudflare credentials
  lines.push('# Cloudflare Credentials');
  lines.push('CLOUDFLARE_ACCOUNT_ID=your-account-id');
  lines.push('CLOUDFLARE_API_TOKEN=your-api-token');
  lines.push('');

  // Alchemy password for secrets encryption
  if (config.secrets.length > 0) {
    lines.push('# Alchemy Secrets Encryption');
    lines.push('# Required for encrypting secrets in state file');
    lines.push('ALCHEMY_PASSWORD=your-encryption-password');
    lines.push('');
  }

  // Application secrets
  if (config.secrets.length > 0) {
    lines.push('# Application Secrets');
    lines.push('# These will be encrypted when stored in state');
    for (const secret of config.secrets) {
      lines.push(`${secret}=your-${secret.toLowerCase().replace(/_/g, '-')}`);
    }
    lines.push('');
  }

  // Plain text vars (optional, for reference)
  if (Object.keys(config.plainTextVars).length > 0) {
    lines.push('# Plain Text Variables (already in alchemy.run.ts)');
    lines.push('# These are shown here for reference only');
    for (const [key, value] of Object.entries(config.plainTextVars)) {
      lines.push(`# ${key}=${value}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
